//+------------------------------------------------------------------+
//|                                           OptimizedEA_20250914_174333_1060 |
//|                                  Generated by QuantTrader Pro v4.2 |
//+------------------------------------------------------------------+
// Strategy: OptimizedEA_20250914_174333_1060
// Trial UID: 20250914_174333:1060
// Optimized on: chart_cl_3.csv
// Generated: 2025-09-14 17:53:42
//+------------------------------------------------------------------+

#property copyright "QuantTrader Pro"
#property link      ""
#property version   "1.00"
#property strict

// Include necessary libraries
#include <Trade/Trade.mqh>
#include <Trade/SymbolInfo.mqh>
#include <Trade/PositionInfo.mqh>
#include <Trade/OrderInfo.mqh>

//--- Input Parameters
input group "=== STRATEGY PARAMETERS ==="
input int      fast_min_len         = 10; // Fast MA minimum length
input int      fast_max_len         = 18; // Fast MA maximum length
input int      slow_min_len         = 28; // Slow MA minimum length
input int      slow_max_len         = 55; // Slow MA maximum length
input int      dma_atr_len          = 12; // DMA ATR period
input int      atr_len              = 16; // ATR period
input double   upper_outer_mult     = 2; // Upper outer band multiplier
input double   lower_outer_mult     = 2; // Lower outer band multiplier
input double   upper_inner_mult     = 1; // Upper inner band multiplier
input double   lower_inner_mult     = 1.4; // Lower inner band multiplier
input int      momentum_len         = 14; // Momentum period
input double   momentum_threshold   = 0.75; // Momentum threshold
input int      momentum_lookback    = 75; // Optimized momentum_lookback
input int      slope_lookback       = 1; // Optimized slope_lookback
input int      rsi_len              = 16; // Optimized rsi_len
input int      rsi_oversold         = 25; // Optimized rsi_oversold
input double   trailing_atr_mult    = 1.5; // Optimized trailing_atr_mult

input group "=== RISK MANAGEMENT ==="
input double   RiskPercent        = 2.0;    // Risk per trade (%)
input double   MaxDrawdown        = 20.0;   // Maximum drawdown (%)
input int      MaxPositions       = 1;     // Maximum concurrent positions
input bool     UseStopLoss        = true;  // Use stop loss
input bool     UseTakeProfit      = true;  // Use take profit

input group "=== TRADING SETTINGS ==="
input double   LotSize            = 0.1;   // Fixed lot size (0 = auto)
input int      Slippage           = 3;     // Maximum slippage (points)
input int      MagicNumber        = 12345; // Magic number
input string   TradeComment       = "20250914_174333:1060"; // Trade comment

//--- Global Variables
CTrade         trade;
CSymbolInfo    symbolInfo;
CPositionInfo  positionInfo;
COrderInfo     orderInfo;

double         currentEquity;
double         maxEquity;
double         currentDrawdown;
datetime       lastBarTime;
bool           tradingAllowed;

// Indicator handles
int            handleMA_Fast;
int            handleMA_Slow;
int            handleATR;

// Indicator buffers
double         ma_fast[];
double         ma_slow[];
double         atr[];

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
  {
   // Initialize trade object
   trade.SetExpertMagicNumber(MagicNumber);
   trade.SetMarginMode();
   trade.SetTypeFillingBySymbol(Symbol());
   
   // Initialize symbol info
   if(!symbolInfo.Name(Symbol()))
     {
      Print("Error initializing symbol info");
      return INIT_FAILED;
     }
   
   // Initialize indicators
   handleMA_Fast = iMA(Symbol(), PERIOD_CURRENT, fast_max_len, 0, MODE_EMA, PRICE_CLOSE);
   handleMA_Slow = iMA(Symbol(), PERIOD_CURRENT, slow_max_len, 0, MODE_EMA, PRICE_CLOSE);
   handleATR = iATR(Symbol(), PERIOD_CURRENT, atr_len);
   
   if(handleMA_Fast == INVALID_HANDLE || handleMA_Slow == INVALID_HANDLE || handleATR == INVALID_HANDLE)
     {
      Print("Error creating indicator handles");
      return INIT_FAILED;
     }
   
   // Initialize arrays
   ArraySetAsSeries(ma_fast, true);
   ArraySetAsSeries(ma_slow, true);
   ArraySetAsSeries(atr, true);
   
   // Initialize variables
   lastBarTime = 0;
   tradingAllowed = true;
   maxEquity = AccountInfoDouble(ACCOUNT_EQUITY);
   
   Print("Expert Advisor initialized successfully");
   return INIT_SUCCEEDED;
  }

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
  {
   // Release indicator handles
   IndicatorRelease(handleMA_Fast);
   IndicatorRelease(handleMA_Slow);
   IndicatorRelease(handleATR);
   
   Print("Expert Advisor deinitialized");
  }

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
  {
   // Check if new bar
   if(!IsNewBar()) return;
   
   // Update risk management
   UpdateRiskManagement();
   
   // Check if trading is allowed
   if(!tradingAllowed) return;
   
   // Update indicator values
   if(!UpdateIndicators()) return;
   
   // Check for entry signals
   int signal = GetEntrySignal();
   
   // Execute trades based on signals
   if(signal == 1) // Buy signal
     {
      if(CanOpenPosition(ORDER_TYPE_BUY))
        {
         OpenPosition(ORDER_TYPE_BUY);
        }
     }
   else if(signal == -1) // Sell signal
     {
      if(CanOpenPosition(ORDER_TYPE_SELL))
        {
         OpenPosition(ORDER_TYPE_SELL);
        }
     }
   
   // Check for exit signals
   CheckExitSignals();
  }

//+------------------------------------------------------------------+
//| Strategy Functions                                               |
//+------------------------------------------------------------------+

//+------------------------------------------------------------------+
//| Get entry signal based on optimized parameters                   |
//+------------------------------------------------------------------+
int GetEntrySignal()
  {
   // Implement your optimized strategy logic here
   // This is a template - customize based on your strategy
   
   // Example: Moving average crossover with ATR filter
   if(ma_fast[1] > ma_slow[1] && ma_fast[2] <= ma_slow[2])
     {
      // Additional filters based on optimized parameters
      if(atr[1] > atr_len * 16 * symbolInfo.Point())
        {
         return 1; // Buy signal
        }
     }
   
   if(ma_fast[1] < ma_slow[1] && ma_fast[2] >= ma_slow[2])
     {
      if(atr[1] > atr_len * 16 * symbolInfo.Point())
        {
         return -1; // Sell signal
        }
     }
   
   return 0; // No signal
  }

//+------------------------------------------------------------------+
//| Check exit signals                                               |
//+------------------------------------------------------------------+
void CheckExitSignals()
  {
   for(int i = 0; i < PositionsTotal(); i++)
     {
      if(positionInfo.SelectByIndex(i))
        {
         if(positionInfo.Symbol() == Symbol() && positionInfo.Magic() == MagicNumber)
           {
            // Implement exit logic here
            // Example: opposite signal closes position
            int signal = GetEntrySignal();
            
            if((positionInfo.PositionType() == POSITION_TYPE_BUY && signal == -1) ||
               (positionInfo.PositionType() == POSITION_TYPE_SELL && signal == 1))
              {
               trade.PositionClose(positionInfo.Ticket());
              }
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| Risk Management Functions                                        |
//+------------------------------------------------------------------+

//+------------------------------------------------------------------+
//| Update risk management variables                                 |
//+------------------------------------------------------------------+
void UpdateRiskManagement()
  {
   currentEquity = AccountInfoDouble(ACCOUNT_EQUITY);
   
   if(currentEquity > maxEquity)
     {
      maxEquity = currentEquity;
     }
   
   currentDrawdown = (maxEquity - currentEquity) / maxEquity * 100.0;
   
   // Disable trading if maximum drawdown exceeded
   if(currentDrawdown > MaxDrawdown)
     {
      tradingAllowed = false;
      Print("Trading disabled due to maximum drawdown: ", currentDrawdown, "%");
     }
  }

//+------------------------------------------------------------------+
//| Calculate position size based on risk                           |
//+------------------------------------------------------------------+
double CalculatePositionSize(double stopLossPoints)
  {
   if(LotSize > 0) return LotSize; // Fixed lot size
   
   double equity = AccountInfoDouble(ACCOUNT_EQUITY);
   double riskAmount = equity * RiskPercent / 100.0;
   double tickValue = symbolInfo.TickValue();
   double tickSize = symbolInfo.TickSize();
   
   double riskPerLot = stopLossPoints * tickValue / tickSize;
   double lotSize = riskAmount / riskPerLot;
   
   // Normalize lot size
   double lotStep = symbolInfo.LotsStep();
   lotSize = NormalizeDouble(lotSize / lotStep, 0) * lotStep;
   
   // Apply limits
   double minLot = symbolInfo.LotsMin();
   double maxLot = symbolInfo.LotsMax();
   
   return MathMax(minLot, MathMin(maxLot, lotSize));
  }

//+------------------------------------------------------------------+
//| Check if can open new position                                  |
//+------------------------------------------------------------------+
bool CanOpenPosition(ENUM_ORDER_TYPE orderType)
  {
   // Check maximum positions
   int currentPositions = 0;
   for(int i = 0; i < PositionsTotal(); i++)
     {
      if(positionInfo.SelectByIndex(i))
        {
         if(positionInfo.Symbol() == Symbol() && positionInfo.Magic() == MagicNumber)
           {
            currentPositions++;
           }
        }
     }
   
   return currentPositions < MaxPositions;
  }

//+------------------------------------------------------------------+
//| Utility Functions                                               |
//+------------------------------------------------------------------+

//+------------------------------------------------------------------+
//| Check if new bar                                                |
//+------------------------------------------------------------------+
bool IsNewBar()
  {
   datetime currentTime = iTime(Symbol(), PERIOD_CURRENT, 0);
   if(currentTime != lastBarTime)
     {
      lastBarTime = currentTime;
      return true;
     }
   return false;
  }

//+------------------------------------------------------------------+
//| Update indicator values                                         |
//+------------------------------------------------------------------+
bool UpdateIndicators()
  {
   if(CopyBuffer(handleMA_Fast, 0, 0, 3, ma_fast) < 3) return false;
   if(CopyBuffer(handleMA_Slow, 0, 0, 3, ma_slow) < 3) return false;
   if(CopyBuffer(handleATR, 0, 0, 2, atr) < 2) return false;
   
   return true;
  }

//+------------------------------------------------------------------+
//| Open position                                                   |
//+------------------------------------------------------------------+
bool OpenPosition(ENUM_ORDER_TYPE orderType)
  {
   double price = (orderType == ORDER_TYPE_BUY) ? symbolInfo.Ask() : symbolInfo.Bid();
   double stopLoss = 0, takeProfit = 0;
   
   // Calculate stop loss and take profit
   if(UseStopLoss || UseTakeProfit)
     {
      double atrValue = atr[1];
      double slDistance = atrValue * 2.0; // 2 ATR stop loss
      double tpDistance = atrValue * 3.0; // 3 ATR take profit
      
      if(orderType == ORDER_TYPE_BUY)
        {
         if(UseStopLoss) stopLoss = price - slDistance;
         if(UseTakeProfit) takeProfit = price + tpDistance;
        }
      else
        {
         if(UseStopLoss) stopLoss = price + slDistance;
         if(UseTakeProfit) takeProfit = price - tpDistance;
        }
     }
   
   // Calculate position size
   double lotSize = CalculatePositionSize(MathAbs(price - stopLoss) / symbolInfo.Point());
   
   // Open position
   bool result = trade.PositionOpen(Symbol(), orderType, lotSize, price, stopLoss, takeProfit, TradeComment);
   
   if(result)
     {
      Print("Position opened: ", EnumToString(orderType), " ", lotSize, " lots at ", price);
     }
   else
     {
      Print("Failed to open position: ", trade.ResultRetcode(), " - ", trade.ResultRetcodeDescription());
     }
   
   return result;
  }

//+------------------------------------------------------------------+