#!/usr/bin/env python3
"""
MQL5 Expert Advisor Code Generator

Generates professional MQL5 Expert Advisors from optimized strategy parameters.
Includes proper risk management, position sizing, and error handling.
"""
from typing import Dict, Any, List, Optional
from numbers import Number
from datetime import datetime


class MQL5Generator:
    """Professional MQL5 Expert Advisor code generator."""
    
    def __init__(self):
        self.template_version = "1.0"
        self.generator_info = "Generated by QuantTrader Pro v4.2"
    
    def generate_expert_advisor(self, params: Dict[str, Any], meta: Dict[str, Any] = None) -> str:
        """Generate complete MQL5 Expert Advisor code."""
        meta = meta or {}
        
        # Merge with V2 defaults to ensure all required logic parameters exist
        v2_params = {
            'base_fast_len': 20,
            'base_slow_len': 50,
            'volatility_atr_short': 5,
            'volatility_atr_long': 100,
            'atr_len': 14,
            'rsi_len': 14,
            'rsi_oversold': 30.0,
            'adx_period': 14,
            'adx_threshold': 25.0,
            'stoch_k': 14,
            'stoch_d': 3,
            'stoch_smooth': 3,
            'upper_outer_mult': 2.0,
            'lower_outer_mult': 2.0,
            'upper_inner_mult': 1.2,
            'lower_inner_mult': 1.2,
            'ranging_trigger_window': 3,
            'max_holding_period': 100,
            'chandelier_atr_multiplier': 3.0,
            'cooldown_bars': 3
        }
        # Update with actual optimized params (stripping 'param_' prefix if present)
        clean_params = {}
        for k, v in params.items():
            key = k.replace('param_', '')
            clean_params[key] = v
            
        v2_params.update(clean_params)
        params = v2_params

        # Extract strategy parameters
        strategy_name = meta.get('strategy_name', 'OptimizedStrategy')
        initial_capital = meta.get('initial_capital', 10000.0)
        fees = meta.get('fees', 0.0005)
        
        code = []
        
        # File header
        code.extend(self._generate_header(strategy_name, meta))
        
        # Input parameters
        code.extend(self._generate_inputs(params, initial_capital, fees, meta))
        
        # Global variables
        code.extend(self._generate_globals())
        
        # Expert initialization
        code.extend(self._generate_on_init(params))
        
        # Expert deinitialization
        code.extend(self._generate_on_deinit())
        
        # Main tick function
        code.extend(self._generate_on_tick(params))
        
        # Strategy logic functions
        code.extend(self._generate_strategy_functions(params))
        
        # Risk management functions
        code.extend(self._generate_risk_management())
        
        # Utility functions
        code.extend(self._generate_utilities())
        
        return '\n'.join(code)
    
    def _generate_header(self, strategy_name: str, meta: Dict[str, Any]) -> List[str]:
        """Generate file header with metadata."""
        trial_uid = meta.get('trial_uid', 'unknown')
        chart = meta.get('chart', 'unknown')
        timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        
        return [
            "//+------------------------------------------------------------------+",
            f"//|                                           {strategy_name:>20} |",
            f"//|                                  {self.generator_info:>30} |",
            "//+------------------------------------------------------------------+",
            f"// Strategy: {strategy_name}",
            f"// Trial UID: {trial_uid}",
            f"// Optimized on: {chart}",
            f"// Generated: {timestamp}",
            "//+------------------------------------------------------------------+",
            "",
            "#property copyright \"QuantTrader Pro\"",
            "#property link      \"\"",
            "#property version   \"1.00\"",
            "#property strict",
            "",
            "// Include necessary libraries",
            "#include <Trade/Trade.mqh>",
            "#include <Trade/SymbolInfo.mqh>",
            "#include <Trade/PositionInfo.mqh>",
            "#include <Trade/OrderInfo.mqh>",
            "",
        ]
    
    def _generate_inputs(self, params: Dict[str, Any], initial_capital: float, fees: float, meta: Dict[str, Any]) -> List[str]:
        """Generate input parameters section."""
        code = [
            "//--- Input Parameters",
            "input group \"=== STRATEGY PARAMETERS ===\"",
        ]
        
        # Convert optimized parameters to inputs
        for param, value in params.items():
            param_type = self._get_mql5_type(param, value)
            coerced_value = self._coerce_value_for_type(value, param_type)
            literal = self._format_mql5_literal(coerced_value, param_type)
            comment = self._get_parameter_comment(param)
            code.append(f"input {param_type:<8} {param:<20} = {literal}; // {comment}")
        
        code.extend([
            "",
            "input group \"=== RISK MANAGEMENT ===\"",
            f"input double   RiskPercent        = 2.0;    // Risk per trade (%)",
            f"input double   MaxDrawdown        = 20.0;   // Maximum drawdown (%)",
            f"input int      MaxPositions       = 1;     // Maximum concurrent positions",
            f"input bool     UseStopLoss        = true;  // Use stop loss",
            f"input bool     UseTakeProfit      = true;  // Use take profit",
            "",
            "input group \"=== TRADING SETTINGS ===\"",
            f"input double   LotSize            = 0.1;   // Fixed lot size (0 = auto)",
            f"input int      Slippage           = 3;     // Maximum slippage (points)",
            f"input int      MagicNumber        = 12345; // Magic number",
            f"input string   TradeComment       = {self._format_mql5_literal(meta.get('trial_uid', 'OptimizedEA'), 'string')}; // Trade comment",
            "",
        ])
        
        return code
    
    def _generate_globals(self) -> List[str]:
        """Generate global variables."""
        return [
            "//--- Global Variables",
            "CTrade         trade;",
            "CSymbolInfo    symbolInfo;",
            "CPositionInfo  positionInfo;",
            "COrderInfo     orderInfo;",
            "",
            "double         currentEquity;",
            "double         maxEquity;",
            "double         currentDrawdown;",
            "datetime       lastBarTime;",
            "bool           tradingAllowed;",
            "",
            "// State variables for strategy logic",
            "int            barsInTrade = 0;",
            "double         highestHighSinceEntry = 0.0;",
            "int            rangingEntryArmed = 0;",
            "double         entryPrice = 0.0;",
            "double         stopPrice = 0.0;",
            "bool           inTrade = false;",
            "",
            "// Indicator handles",
            "int            handleMA_Fast;",
            "int            handleMA_Slow;",
            "int            handleATR;",
            "int            handleATR_Short;",
            "int            handleATR_Long;",
            "int            handleADX;",
            "int            handleStoch;",
            "",
            "// Indicator buffers",
            "double         ma_fast[];",
            "double         ma_slow[];",
            "double         atr[];",
            "double         atr_short[];",
            "double         atr_long[];",
            "double         adx[];",
            "double         stoch_k[];",
            "double         stoch_d[];",
            "",
            "// Dynamic DMA buffers",
            "double         fast_dma[];",
            "double         slow_dma[];",
            "",
            "// Margin and position limits",
            "const double   MAX_MARGIN_USAGE_PCT = 40.0;  // Max 40% of equity used for margin",
            "const double   MIN_FREE_MARGIN_PCT = 30.0;   // Keep at least 30% free margin",
            "const double   MAX_LOTS_PER_SYMBOL = 5.0;     // Max lots per symbol",
            "const double   COMMISSION_PER_LOT = 7.0;      // USD per lot round-trip",
            "const double   COMMISSION_PER_SIDE = 3.5;     // USD per lot per side",
            "",
        ]
    
    def _generate_on_init(self, params: Dict[str, Any]) -> List[str]:
        """Generate OnInit function."""
        # Resolve parameter names (or sensible defaults) to avoid undeclared identifiers
        fast_len_expr = self._select_param_expr(params, ['base_fast_len', 'fast_len'], 20)
        slow_len_expr = self._select_param_expr(params, ['base_slow_len', 'slow_len'], 50)
        atr_len_expr = self._select_param_expr(params, ['atr_len'], 14)
        atr_short_expr = self._select_param_expr(params, ['volatility_atr_short'], 5)
        atr_long_expr = self._select_param_expr(params, ['volatility_atr_long'], 100)
        adx_expr = self._select_param_expr(params, ['adx_period'], 14)
        stoch_k_expr = self._select_param_expr(params, ['stoch_k'], 14)
        stoch_d_expr = self._select_param_expr(params, ['stoch_d'], 3)
        stoch_smooth_expr = self._select_param_expr(params, ['stoch_smooth'], 3)

        return [
            "//+------------------------------------------------------------------+",
            "//| Expert initialization function                                   |",
            "//+------------------------------------------------------------------+",
            "int OnInit()",
            "  {",
            "   // Initialize trade object",
            "   trade.SetExpertMagicNumber(MagicNumber);",
            "   trade.SetMarginMode();",
            "   trade.SetTypeFillingBySymbol(Symbol());",
            "   ",
            "   // Initialize symbol info",
            "   if(!symbolInfo.Name(Symbol()))",
            "     {",
            "      Print(\"Error initializing symbol info\");",
            "      return INIT_FAILED;",
            "     }",
            "   ",
            "   // Initialize indicators",
            f"   handleMA_Fast = iMA(Symbol(), PERIOD_CURRENT, {fast_len_expr}, 0, MODE_EMA, PRICE_CLOSE);",
            f"   handleMA_Slow = iMA(Symbol(), PERIOD_CURRENT, {slow_len_expr}, 0, MODE_EMA, PRICE_CLOSE);",
            f"   handleATR = iATR(Symbol(), PERIOD_CURRENT, {atr_len_expr});",
            f"   handleATR_Short = iATR(Symbol(), PERIOD_CURRENT, {atr_short_expr});",
            f"   handleATR_Long = iATR(Symbol(), PERIOD_CURRENT, {atr_long_expr});",
            f"   handleADX = iADX(Symbol(), PERIOD_CURRENT, {adx_expr});",
            f"   handleStoch = iStochastic(Symbol(), PERIOD_CURRENT, {stoch_k_expr}, {stoch_d_expr}, {stoch_smooth_expr}, MODE_SMA, STO_LOWHIGH);",
            "   ",
            "   if(handleMA_Fast == INVALID_HANDLE || handleMA_Slow == INVALID_HANDLE || handleATR == INVALID_HANDLE ||",
            "      handleATR_Short == INVALID_HANDLE || handleATR_Long == INVALID_HANDLE ||",
            "      handleADX == INVALID_HANDLE || handleStoch == INVALID_HANDLE)",
            "     {",
            "      Print(\"Error creating indicator handles\");",
            "      return INIT_FAILED;",
            "     }",
            "   ",
            "   // Initialize arrays",
            "   ArraySetAsSeries(ma_fast, true);",
            "   ArraySetAsSeries(ma_slow, true);",
            "   ArraySetAsSeries(atr, true);",
            "   ArraySetAsSeries(atr_short, true);",
            "   ArraySetAsSeries(atr_long, true);",
            "   ArraySetAsSeries(adx, true);",
            "   ArraySetAsSeries(stoch_k, true);",
            "   ArraySetAsSeries(stoch_d, true);",
            "   ",
            "   // Initialize variables",
            "   lastBarTime = 0;",
            "   tradingAllowed = true;",
            "   maxEquity = AccountInfoDouble(ACCOUNT_EQUITY);",
            "   ",
            "   Print(\"Expert Advisor initialized successfully\");",
            "   return INIT_SUCCEEDED;",
            "  }",
            "",
        ]
    
    def _generate_on_deinit(self) -> List[str]:
        """Generate OnDeinit function."""
        return [
            "//+------------------------------------------------------------------+",
            "//| Expert deinitialization function                                 |",
            "//+------------------------------------------------------------------+",
            "void OnDeinit(const int reason)",
            "  {",
            "   // Release indicator handles",
            "   IndicatorRelease(handleMA_Fast);",
            "   IndicatorRelease(handleMA_Slow);",
            "   IndicatorRelease(handleATR);",
            "   ",
            "   Print(\"Expert Advisor deinitialized\");",
            "  }",
            "",
        ]
    
    def _generate_on_tick(self, params: Dict[str, Any]) -> List[str]:
        """Generate main OnTick function."""
        return [
            "//+------------------------------------------------------------------+",
            "//| Expert tick function                                             |",
            "//+------------------------------------------------------------------+",
            "void OnTick()",
            "  {",
            "   // Check if new bar",
            "   if(!IsNewBar()) return;",
            "   ",
            "   // Update risk management",
            "   UpdateRiskManagement();",
            "   ",
            "   // Check if trading is allowed",
            "   if(!tradingAllowed) return;",
            "   ",
            "   // Update indicator values",
            "   if(!UpdateIndicators()) return;",
            "   ",
            "   // Check for entry signals",
            "   int signal = GetEntrySignal();",
            "   ",
            "   // Execute trades based on signals",
            "   if(signal == 1) // Buy signal",
            "     {",
            "      if(CanOpenPosition(ORDER_TYPE_BUY))",
            "        {",
            "         OpenPosition(ORDER_TYPE_BUY);",
            "        }",
            "     }",
            "   else if(signal == -1) // Sell signal",
            "     {",
            "      if(CanOpenPosition(ORDER_TYPE_SELL))",
            "        {",
            "         OpenPosition(ORDER_TYPE_SELL);",
            "        }",
            "     }",
            "   ",
            "   // Check for exit signals",
            "   CheckExitSignals();",
            "  }",
            "",
        ]
    
    def _generate_strategy_functions(self, params: Dict[str, Any]) -> List[str]:
        """Generate strategy-specific functions."""
        return [
            "//+------------------------------------------------------------------+",
            "//| Strategy Functions                                               |",
            "//+------------------------------------------------------------------+",
            "",
            "//+------------------------------------------------------------------+",
            "//| Get entry signal based on optimized parameters                   |",
            "//+------------------------------------------------------------------+",
            "int GetEntrySignal()",
            "  {",
            "   // Regime Definition",
            "   bool isTrending = fast_dma[0] > slow_dma[0];",
            "   double low = iLow(Symbol(), PERIOD_CURRENT, 0);",
            "   double close = iClose(Symbol(), PERIOD_CURRENT, 0);",
            "   double open = iOpen(Symbol(), PERIOD_CURRENT, 0);",
            "   ",
            "   // Arm ranging setup when regime is range and conditions satisfy",
            "   if(!isTrending && low < (slow_dma[0] - lower_outer_mult * atr[0]) && rsi[0] < rsi_oversold)",
            "     {",
            "      rangingEntryArmed = (int)ranging_trigger_window;",
            "     }",
            "   else if(rangingEntryArmed > 0)",
            "     {",
            "      rangingEntryArmed--;",
            "     }",
            "   ",
            "   // 1) Trending Entry: Golden Zone pullback with Stochastic confirmation",
            "   bool inGoldenZone = isTrending && (low <= fast_dma[0]);",
            "   bool stochCrossUp = (stoch_k[0] > stoch_d[0]) && (stoch_k[1] <= stoch_d[1]);",
            "   if(inGoldenZone && stochCrossUp) return 1; // Trending Buy signal",
            "   ",
            "   // 2) Ranging Entry: Armed trigger with confirmation bar",
            "   bool isReversalBar = close > open;",
            "   if(rangingEntryArmed > 0 && isReversalBar) return 1; // Ranging Buy signal",
            "   ",
            "   return 0; // No signal",
            "  }",
            "",
            "//+------------------------------------------------------------------+",
            "//| Check exit signals                                               |",
            "//+------------------------------------------------------------------+",
            "void CheckExitSignals()",
            "  {",
            "   if(!inTrade) return;",
            "   ",
            "   barsInTrade++;",
            "   double high = iHigh(Symbol(), PERIOD_CURRENT, 0);",
            "   double low = iLow(Symbol(), PERIOD_CURRENT, 0);",
            "   double close = iClose(Symbol(), PERIOD_CURRENT, 0);",
            "   ",
            "   if(high > highestHighSinceEntry) highestHighSinceEntry = high;",
            "   ",
            "   // Hierarchical stops",
            "   bool timeStop = barsInTrade >= max_holding_period;",
            "   bool adxStop = (fast_dma[0] > slow_dma[0]) && (adx[0] < adx_threshold);",
            "   ",
            "   double chandelierStop = highestHighSinceEntry - (atr[0] * chandelier_atr_multiplier);",
            "   bool chandelierHit = low < chandelierStop;",
            "   ",
            "   bool trendInvalidation = close < slow_dma[0];",
            "   ",
            "   double upperInner = fast_dma[0] + upper_inner_mult * atr[0];",
            "   bool rangeProfitExit = (fast_dma[0] <= slow_dma[0]) && (high >= upperInner);",
            "   ",
            "   if(timeStop || adxStop || chandelierHit || trendInvalidation || rangeProfitExit)",
            "     {",
            "      for(int i = 0; i < PositionsTotal(); i++)",
            "        {",
            "         if(positionInfo.SelectByIndex(i))",
            "           {",
            "            if(positionInfo.Symbol() == Symbol() && positionInfo.Magic() == MagicNumber)",
            "              {",
            "               trade.PositionClose(positionInfo.Ticket());",
            "               inTrade = false;",
            "               barsInTrade = 0;",
            "               highestHighSinceEntry = 0.0;",
            "               rangingEntryArmed = 0;",
            "              }",
            "           }",
            "        }",
            "     }",
            "  }",
            "",
        ]
    
    def _generate_risk_management(self) -> List[str]:
        """Generate risk management functions."""
        return [
            "//+------------------------------------------------------------------+",
            "//| Risk Management Functions                                        |",
            "//+------------------------------------------------------------------+",
            "",
            "//+------------------------------------------------------------------+",
            "//| Update risk management variables                                 |",
            "//+------------------------------------------------------------------+",
            "void UpdateRiskManagement()",
            "  {",
            "   currentEquity = AccountInfoDouble(ACCOUNT_EQUITY);",
            "   ",
            "   if(currentEquity > maxEquity)",
            "     {",
            "      maxEquity = currentEquity;",
            "     }",
            "   ",
            "   currentDrawdown = (maxEquity - currentEquity) / maxEquity * 100.0;",
            "   ",
            "   // Disable trading if maximum drawdown exceeded",
            "   if(currentDrawdown > MaxDrawdown)",
            "     {",
            "      tradingAllowed = false;",
            "      Print(\"Trading disabled due to maximum drawdown: \", currentDrawdown, \"%\");",
            "     }",
            "  }",
            "",
            "//+------------------------------------------------------------------+",
            "//| Calculate position size based on risk                           |",
            "//+------------------------------------------------------------------+",
            "double CalculatePositionSize(double stopLossPoints)",
            "  {",
            "   if(LotSize > 0) return LotSize; // Fixed lot size",
            "   ",
            "   double equity = AccountInfoDouble(ACCOUNT_EQUITY);",
            "   double riskAmount = equity * RiskPercent / 100.0;",
            "   double tickValue = symbolInfo.TickValue();",
            "   double tickSize = symbolInfo.TickSize();",
            "   ",
            "   double riskPerLot = stopLossPoints * tickValue / tickSize;",
            "   double lotSize = riskAmount / riskPerLot;",
            "   ",
            "   // Normalize lot size",
            "   double lotStep = symbolInfo.LotsStep();",
            "   lotSize = NormalizeDouble(lotSize / lotStep, 0) * lotStep;",
            "   ",
            "   // Apply limits",
            "   double minLot = symbolInfo.LotsMin();",
            "   double maxLot = symbolInfo.LotsMax();",
            "   ",
            "   return MathMax(minLot, MathMin(maxLot, lotSize));",
            "  }",
            "",
            "//+------------------------------------------------------------------+",
            "//| Check if can open new position                                  |",
            "//+------------------------------------------------------------------+",
            "bool CanOpenPosition(ENUM_ORDER_TYPE orderType)",
            "  {",
            "   // Check maximum positions",
            "   int currentPositions = 0;",
            "   for(int i = 0; i < PositionsTotal(); i++)",
            "     {",
            "      if(positionInfo.SelectByIndex(i))",
            "        {",
            "         if(positionInfo.Symbol() == Symbol() && positionInfo.Magic() == MagicNumber)",
            "           {",
            "            currentPositions++;",
            "           }",
            "        }",
            "     }",
            "   ",
            "   if(currentPositions >= MaxPositions)",
            "     {",
            "      return false;",
            "     }",
            "   ",
            "   // Check max lots per symbol",
            "   double totalLots = 0.0;",
            "   for(int i = 0; i < PositionsTotal(); i++)",
            "     {",
            "      if(positionInfo.SelectByIndex(i))",
            "        {",
            "         if(positionInfo.Symbol() == Symbol() && positionInfo.Magic() == MagicNumber)",
            "           {",
            "            totalLots += positionInfo.Volume();",
            "           }",
            "        }",
            "     }",
            "   ",
            "   // Use maximum possible lot size for conservative margin check",
            "   double maxLotSize = symbolInfo.LotsMax();",
            "   if(totalLots + maxLotSize > MAX_LOTS_PER_SYMBOL)",
            "     {",
            "      Print(\"Max lots per symbol exceeded: \", totalLots, \" + \", maxLotSize, \" > \", MAX_LOTS_PER_SYMBOL);",
            "      return false;",
            "     }",
            "   ",
            "   // Calculate required margin for maximum lot size (conservative check)",
            "   double price = (orderType == ORDER_TYPE_BUY) ? symbolInfo.Ask() : symbolInfo.Bid();",
            "   double requiredMargin = 0.0;",
            "   if(!OrderCalcMargin(orderType, Symbol(), maxLotSize, price, requiredMargin))",
            "     {",
            "      Print(\"Failed to calculate margin for \", Symbol());",
            "      return false;",
            "     }",
            "   ",
            "   // Get account info",
            "   double equity = AccountInfoDouble(ACCOUNT_EQUITY);",
            "   double freeMargin = AccountInfoDouble(ACCOUNT_MARGIN_FREE);",
            "   double currentMargin = AccountInfoDouble(ACCOUNT_MARGIN);",
            "   ",
            "   // Check max margin usage (40% of equity)",
            "   if((currentMargin + requiredMargin) > equity * MAX_MARGIN_USAGE_PCT / 100.0)",
            "     {",
            "      Print(\"Max margin usage exceeded: \", (currentMargin + requiredMargin), \" > \", equity * MAX_MARGIN_USAGE_PCT / 100.0);",
            "      return false;",
            "     }",
            "   ",
            "   // Check min free margin (30% of equity)",
            "   if((freeMargin - requiredMargin) < equity * MIN_FREE_MARGIN_PCT / 100.0)",
            "     {",
            "      Print(\"Insufficient free margin buffer: \", (freeMargin - requiredMargin), \" < \", equity * MIN_FREE_MARGIN_PCT / 100.0);",
            "      return false;",
            "     }",
            "   ",
            "   return true;",
            "  }",
            "",
        ]
    
    def _generate_utilities(self) -> List[str]:
        """Generate utility functions."""
        return [
            "//+------------------------------------------------------------------+",
            "//| Utility Functions                                               |",
            "//+------------------------------------------------------------------+",
            "",
            "//+------------------------------------------------------------------+",
            "//| Check if new bar                                                |",
            "//+------------------------------------------------------------------+",
            "bool IsNewBar()",
            "  {",
            "   datetime currentTime = iTime(Symbol(), PERIOD_CURRENT, 0);",
            "   if(currentTime != lastBarTime)",
            "     {",
            "      lastBarTime = currentTime;",
            "      return true;",
            "     }",
            "   return false;",
            "  }",
            "",
            "//+------------------------------------------------------------------+",
            "//| Update indicator values                                         |",
            "//+------------------------------------------------------------------+",
            "bool UpdateIndicators()",
            "  {",
            "   if(CopyBuffer(handleMA_Fast, 0, 0, 3, ma_fast) < 3) return false;",
            "   if(CopyBuffer(handleMA_Slow, 0, 0, 3, ma_slow) < 3) return false;",
            "   if(CopyBuffer(handleATR, 0, 0, 3, atr) < 3) return false;",
            "   if(CopyBuffer(handleATR_Short, 0, 0, 3, atr_short) < 3) return false;",
            "   if(CopyBuffer(handleATR_Long, 0, 0, 3, atr_long) < 3) return false;",
            "   if(CopyBuffer(handleADX, 0, 0, 3, adx) < 3) return false;",
            "   if(CopyBuffer(handleStoch, 0, 0, 3, stoch_k) < 3) return false;",
            "   if(CopyBuffer(handleStoch, 1, 0, 3, stoch_d) < 3) return false;",
            "   ",
            "   // Update Dynamic EMAs (DMA)",
            "   CalculateDynamicEMAs();",
            "   ",
            "   return true;",
            "  }",
            "",
            "//+------------------------------------------------------------------+",
            "//| Calculate Dynamic EMAs (DMA) using volatility scaling           |",
            "//+------------------------------------------------------------------+",
            "void CalculateDynamicEMAs()",
            "  {",
            "   double close = iClose(Symbol(), PERIOD_CURRENT, 0);",
            "   double v_idx = (atr_long[0] > 0) ? (atr_short[0] / atr_long[0]) : 1.0;",
            "   if(v_idx < 0.25) v_idx = 0.25; if(v_idx > 4.0) v_idx = 4.0;",
            "   ",
            "   // Note: In real MT5, we would use an indicator buffer for history.",
            "   // For this snippet, we'll update the latest value using the previous bar's DMA.",
            "   // This matches the Python vectorized logic bar-by-bar.",
            "   double fast_len = base_fast_len / (v_idx + 1e-12);",
            "   double slow_len = base_slow_len * (v_idx + 1e-12);",
            "   ",
            "   // Alpha = 2 / (Length + 1)",
            "   double alpha_f = 2.0 / (fast_len + 1.0);",
            "   double alpha_s = 2.0 / (slow_len + 1.0);",
            "   ",
            "   // ArrayResize if needed",
            "   if(ArraySize(fast_dma) < 2) { ArrayResize(fast_dma, 2); fast_dma[1] = close; }",
            "   if(ArraySize(slow_dma) < 2) { ArrayResize(slow_dma, 2); slow_dma[1] = close; }",
            "   ",
            "   fast_dma[0] = alpha_f * close + (1.0 - alpha_f) * fast_dma[1];",
            "   slow_dma[0] = alpha_s * close + (1.0 - alpha_s) * slow_dma[1];",
            "   ",
            "   // Shift for next tick",
            "   fast_dma[1] = fast_dma[0];",
            "   slow_dma[1] = slow_dma[0];",
            "  }",
            "",
            "//+------------------------------------------------------------------+",
            "//| Open position                                                   |",
            "//+------------------------------------------------------------------+",
            "bool OpenPosition(ENUM_ORDER_TYPE orderType)",
            "  {",
            "   double price = (orderType == ORDER_TYPE_BUY) ? symbolInfo.Ask() : symbolInfo.Bid();",
            "   double stopLoss = 0, takeProfit = 0;",
            "   ",
            "   // Calculate stop loss and take profit",
            "   if(UseStopLoss || UseTakeProfit)",
            "     {",
            "      double atrValue = atr[1];",
            "      double slDistance = atrValue * 2.0; // 2 ATR stop loss",
            "      double tpDistance = atrValue * 3.0; // 3 ATR take profit",
            "      ",
            "      if(orderType == ORDER_TYPE_BUY)",
            "        {",
            "         if(UseStopLoss) stopLoss = price - slDistance;",
            "         if(UseTakeProfit) takeProfit = price + tpDistance;",
            "        }",
            "      else",
            "        {",
            "         if(UseStopLoss) stopLoss = price + slDistance;",
            "         if(UseTakeProfit) takeProfit = price - tpDistance;",
            "        }",
            "     }",
            "   ",
            "   // Calculate position size",
            "   double lotSize = CalculatePositionSize(MathAbs(price - stopLoss) / symbolInfo.Point());",
            "   ",
            "   // Final margin check with actual lot size",
            "   double requiredMargin = 0.0;",
            "   if(!OrderCalcMargin(orderType, Symbol(), lotSize, price, requiredMargin))",
            "     {",
            "      Print(\"Failed to calculate margin for \", Symbol());",
            "      return false;",
            "     }",
            "   ",
            "   double equity = AccountInfoDouble(ACCOUNT_EQUITY);",
            "   double freeMargin = AccountInfoDouble(ACCOUNT_MARGIN_FREE);",
            "   double currentMargin = AccountInfoDouble(ACCOUNT_MARGIN);",
            "   ",
            "   // Check max margin usage (40% of equity)",
            "   if((currentMargin + requiredMargin) > equity * MAX_MARGIN_USAGE_PCT / 100.0)",
            "     {",
            "      Print(\"Max margin usage exceeded: \", (currentMargin + requiredMargin), \" > \", equity * MAX_MARGIN_USAGE_PCT / 100.0);",
            "      return false;",
            "     }",
            "   ",
            "   // Check min free margin (30% of equity)",
            "   if((freeMargin - requiredMargin) < equity * MIN_FREE_MARGIN_PCT / 100.0)",
            "     {",
            "      Print(\"Insufficient free margin buffer: \", (freeMargin - requiredMargin), \" < \", equity * MIN_FREE_MARGIN_PCT / 100.0);",
            "      return false;",
            "     }",
            "   ",
            "   // Open position",
            "   bool result = trade.PositionOpen(Symbol(), orderType, lotSize, price, stopLoss, takeProfit, TradeComment);",
            "   ",
            "   if(result)",
            "     {",
            "      Print(\"Position opened: \", EnumToString(orderType), \" \", lotSize, \" lots at \", price);",
            "      inTrade = true;",
            "      barsInTrade = 0;",
            "      entryPrice = price;",
            "      highestHighSinceEntry = price;",
            "     }",
            "   else",
            "     {",
            "      Print(\"Failed to open position: \", trade.ResultRetcode(), \" - \", trade.ResultRetcodeDescription());",
            "     }",
            "   ",
            "   return result;",
            "  }",
            "",
            "//+------------------------------------------------------------------+",
        ]
    
    def _get_mql5_type(self, param_name: str, value: Any) -> str:
        """Infer appropriate MQL5 input type for a parameter using name and value."""
        name = param_name.lower()

        # Explicit name-based mapping first (prevents numeric-looking strings from becoming string inputs)
        if (name.endswith(('_min_len', '_max_len', '_len')) or
            name.endswith('len') or
            any(k in name for k in ['period', 'lookback', 'bars', 'window'])):
            return 'int'

        if any(k in name for k in ['mult', 'ratio', 'threshold', 'factor']):
            return 'double'

        if name.startswith(('use', 'enable', 'disable')):
            return 'bool'

        # Fallback to value-based inference
        if isinstance(value, bool):
            return 'bool'
        if isinstance(value, int):
            return 'int'
        if isinstance(value, float):
            return 'double'
        
        # Strings that look like numbers: try to infer
        if isinstance(value, str):
            v = value.strip()
            # Detect boolean-like strings
            if v.lower() in ('true', 'false', 'yes', 'no', '1', '0'):
                return 'bool'
            # Detect integer-like
            try:
                # Accept forms like "12", "12.0"
                f = float(v)
                if f.is_integer():
                    return 'int'
                return 'double'
            except Exception:
                return 'string'

        return 'string'

    def _coerce_value_for_type(self, value: Any, mql_type: str) -> Any:
        """Coerce Python value to an appropriate Python type for the target MQL type."""
        try:
            if mql_type == 'bool':
                if isinstance(value, bool):
                    return value
                if isinstance(value, Number):
                    return bool(value)
                if isinstance(value, str):
                    v = value.strip().lower()
                    if v in ('true', 'yes', '1'):
                        return True
                    if v in ('false', 'no', '0'):
                        return False
                return False
            if mql_type == 'int':
                if isinstance(value, int):
                    return value
                if isinstance(value, Number):
                    return int(round(float(value)))
                if isinstance(value, str):
                    v = value.strip()
                    # Allow "12", "12.0"
                    f = float(v)
                    return int(round(f))
                return 0
            if mql_type == 'double':
                if isinstance(value, Number):
                    return float(value)
                if isinstance(value, str):
                    v = value.strip()
                    return float(v)
                return 0.0
            # string
            if value is None:
                return ''
            return str(value)
        except Exception:
            # Conservative defaults on parse failure
            if mql_type == 'bool':
                return False
            if mql_type == 'int':
                return 0
            if mql_type == 'double':
                return 0.0
            return ''

    def _format_mql5_literal(self, value: Any, mql_type: str) -> str:
        """Format a Python value as an MQL5 literal for the given type."""
        if mql_type == 'bool':
            return 'true' if bool(value) else 'false'
        if mql_type == 'int':
            try:
                return str(int(value))
            except Exception:
                return '0'
        if mql_type == 'double':
            try:
                # Compact yet precise representation
                return ("%g" % float(value))
            except Exception:
                return '0.0'
        # string
        s = '' if value is None else str(value)
        s = s.replace('\\', '\\\\').replace('"', '\\"')
        return f'"{s}"'
    
    def _get_parameter_comment(self, param_name: str) -> str:
        """Get descriptive comment for a parameter."""
        comments = {
            'fast_min_len': 'Fast MA minimum length',
            'fast_max_len': 'Fast MA maximum length', 
            'slow_min_len': 'Slow MA minimum length',
            'slow_max_len': 'Slow MA maximum length',
            'atr_len': 'ATR period',
            'dma_atr_len': 'DMA ATR period',
            'upper_outer_mult': 'Upper outer band multiplier',
            'lower_outer_mult': 'Lower outer band multiplier',
            'upper_inner_mult': 'Upper inner band multiplier',
            'lower_inner_mult': 'Lower inner band multiplier',
            'momentum_len': 'Momentum period',
            'momentum_threshold': 'Momentum threshold'
        }
        return comments.get(param_name, f'Optimized {param_name}')

    def _select_param_expr(self, params: Dict[str, Any], candidates: List[str], default_value: int | float) -> str:
        """Return the MQL5 expression to use for a parameter: prefer an input name that exists, else a literal.

        This prevents referencing undeclared identifiers when a particular parameter name is absent.
        """
        for name in candidates:
            if name in params:
                return name
        # Fallback to numeric literal
        if isinstance(default_value, int):
            return str(default_value)
        try:
            return ("%g" % float(default_value))
        except Exception:
            return "0"
