#!/usr/bin/env python3
"""
MQL5 Expert Advisor Code Generator

Generates professional MQL5 Expert Advisors from optimized strategy parameters.
Includes proper risk management, position sizing, and error handling.
"""
from typing import Dict, Any, List, Optional
from numbers import Number
from datetime import datetime


class MQL5Generator:
    """Professional MQL5 Expert Advisor code generator."""
    
    def __init__(self):
        self.template_version = "1.0"
        self.generator_info = "Generated by QuantTrader Pro v4.2"
    
    def generate_expert_advisor(self, params: Dict[str, Any], meta: Dict[str, Any] = None) -> str:
        """Generate complete MQL5 Expert Advisor code."""
        meta = meta or {}
        
        # Extract strategy parameters
        strategy_name = meta.get('strategy_name', 'OptimizedStrategy')
        initial_capital = meta.get('initial_capital', 10000.0)
        fees = meta.get('fees', 0.0005)
        
        code = []
        
        # File header
        code.extend(self._generate_header(strategy_name, meta))
        
        # Input parameters
        code.extend(self._generate_inputs(params, initial_capital, fees, meta))
        
        # Global variables
        code.extend(self._generate_globals())
        
        # Expert initialization
        code.extend(self._generate_on_init(params))
        
        # Expert deinitialization
        code.extend(self._generate_on_deinit())
        
        # Main tick function
        code.extend(self._generate_on_tick(params))
        
        # Strategy logic functions
        code.extend(self._generate_strategy_functions(params))
        
        # Risk management functions
        code.extend(self._generate_risk_management())
        
        # Utility functions
        code.extend(self._generate_utilities())
        
        return '\n'.join(code)
    
    def _generate_header(self, strategy_name: str, meta: Dict[str, Any]) -> List[str]:
        """Generate file header with metadata."""
        trial_uid = meta.get('trial_uid', 'unknown')
        chart = meta.get('chart', 'unknown')
        timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        
        return [
            "//+------------------------------------------------------------------+",
            f"//|                                           {strategy_name:>20} |",
            f"//|                                  {self.generator_info:>30} |",
            "//+------------------------------------------------------------------+",
            f"// Strategy: {strategy_name}",
            f"// Trial UID: {trial_uid}",
            f"// Optimized on: {chart}",
            f"// Generated: {timestamp}",
            "//+------------------------------------------------------------------+",
            "",
            "#property copyright \"QuantTrader Pro\"",
            "#property link      \"\"",
            "#property version   \"1.00\"",
            "#property strict",
            "",
            "// Include necessary libraries",
            "#include <Trade/Trade.mqh>",
            "#include <Trade/SymbolInfo.mqh>",
            "#include <Trade/PositionInfo.mqh>",
            "#include <Trade/OrderInfo.mqh>",
            "",
        ]
    
    def _generate_inputs(self, params: Dict[str, Any], initial_capital: float, fees: float, meta: Dict[str, Any]) -> List[str]:
        """Generate input parameters section."""
        code = [
            "//--- Input Parameters",
            "input group \"=== STRATEGY PARAMETERS ===\"",
        ]
        
        # Convert optimized parameters to inputs
        for param, value in params.items():
            param_type = self._get_mql5_type(param, value)
            coerced_value = self._coerce_value_for_type(value, param_type)
            literal = self._format_mql5_literal(coerced_value, param_type)
            comment = self._get_parameter_comment(param)
            code.append(f"input {param_type:<8} {param:<20} = {literal}; // {comment}")
        
        code.extend([
            "",
            "input group \"=== RISK MANAGEMENT ===\"",
            f"input double   RiskPercent        = 2.0;    // Risk per trade (%)",
            f"input double   MaxDrawdown        = 20.0;   // Maximum drawdown (%)",
            f"input int      MaxPositions       = 1;     // Maximum concurrent positions",
            f"input bool     UseStopLoss        = true;  // Use stop loss",
            f"input bool     UseTakeProfit      = true;  // Use take profit",
            "",
            "input group \"=== TRADING SETTINGS ===\"",
            f"input double   LotSize            = 0.1;   // Fixed lot size (0 = auto)",
            f"input int      Slippage           = 3;     // Maximum slippage (points)",
            f"input int      MagicNumber        = 12345; // Magic number",
            f"input string   TradeComment       = {self._format_mql5_literal(meta.get('trial_uid', 'OptimizedEA'), 'string')}; // Trade comment",
            "",
        ])
        
        return code
    
    def _generate_globals(self) -> List[str]:
        """Generate global variables."""
        return [
            "//--- Global Variables",
            "CTrade         trade;",
            "CSymbolInfo    symbolInfo;",
            "CPositionInfo  positionInfo;",
            "COrderInfo     orderInfo;",
            "",
            "double         currentEquity;",
            "double         maxEquity;",
            "double         currentDrawdown;",
            "datetime       lastBarTime;",
            "bool           tradingAllowed;",
            "",
            "// Indicator handles",
            "int            handleMA_Fast;",
            "int            handleMA_Slow;",
            "int            handleATR;",
            "",
            "// Indicator buffers",
            "double         ma_fast[];",
            "double         ma_slow[];",
            "double         atr[];",
            "",
        ]
    
    def _generate_on_init(self, params: Dict[str, Any]) -> List[str]:
        """Generate OnInit function."""
        # Resolve parameter names (or sensible defaults) to avoid undeclared identifiers
        fast_len_expr = self._select_param_expr(
            params,
            candidates=[
                'base_fast_len', 'fast_len', 'fast_max_len', 'fast_min_len',
                'ema_fast_len', 'sma_fast_len', 'trend_fast_len'
            ],
            default_value=14,
        )
        slow_len_expr = self._select_param_expr(
            params,
            candidates=[
                'base_slow_len', 'slow_len', 'slow_max_len', 'slow_min_len',
                'ema_slow_len', 'sma_slow_len', 'trend_slow_len'
            ],
            default_value=50,
        )
        atr_len_expr = self._select_param_expr(
            params,
            candidates=['atr_len', 'volatility_atr_len', 'dma_atr_len'],
            default_value=14,
        )
        return [
            "//+------------------------------------------------------------------+",
            "//| Expert initialization function                                   |",
            "//+------------------------------------------------------------------+",
            "int OnInit()",
            "  {",
            "   // Initialize trade object",
            "   trade.SetExpertMagicNumber(MagicNumber);",
            "   trade.SetMarginMode();",
            "   trade.SetTypeFillingBySymbol(Symbol());",
            "   ",
            "   // Initialize symbol info",
            "   if(!symbolInfo.Name(Symbol()))",
            "     {",
            "      Print(\"Error initializing symbol info\");",
            "      return INIT_FAILED;",
            "     }",
            "   ",
            "   // Initialize indicators",
            f"   handleMA_Fast = iMA(Symbol(), PERIOD_CURRENT, {fast_len_expr}, 0, MODE_EMA, PRICE_CLOSE);",
            f"   handleMA_Slow = iMA(Symbol(), PERIOD_CURRENT, {slow_len_expr}, 0, MODE_EMA, PRICE_CLOSE);",
            f"   handleATR = iATR(Symbol(), PERIOD_CURRENT, {atr_len_expr});",
            "   ",
            "   if(handleMA_Fast == INVALID_HANDLE || handleMA_Slow == INVALID_HANDLE || handleATR == INVALID_HANDLE)",
            "     {",
            "      Print(\"Error creating indicator handles\");",
            "      return INIT_FAILED;",
            "     }",
            "   ",
            "   // Initialize arrays",
            "   ArraySetAsSeries(ma_fast, true);",
            "   ArraySetAsSeries(ma_slow, true);",
            "   ArraySetAsSeries(atr, true);",
            "   ",
            "   // Initialize variables",
            "   lastBarTime = 0;",
            "   tradingAllowed = true;",
            "   maxEquity = AccountInfoDouble(ACCOUNT_EQUITY);",
            "   ",
            "   Print(\"Expert Advisor initialized successfully\");",
            "   return INIT_SUCCEEDED;",
            "  }",
            "",
        ]
    
    def _generate_on_deinit(self) -> List[str]:
        """Generate OnDeinit function."""
        return [
            "//+------------------------------------------------------------------+",
            "//| Expert deinitialization function                                 |",
            "//+------------------------------------------------------------------+",
            "void OnDeinit(const int reason)",
            "  {",
            "   // Release indicator handles",
            "   IndicatorRelease(handleMA_Fast);",
            "   IndicatorRelease(handleMA_Slow);",
            "   IndicatorRelease(handleATR);",
            "   ",
            "   Print(\"Expert Advisor deinitialized\");",
            "  }",
            "",
        ]
    
    def _generate_on_tick(self, params: Dict[str, Any]) -> List[str]:
        """Generate main OnTick function."""
        return [
            "//+------------------------------------------------------------------+",
            "//| Expert tick function                                             |",
            "//+------------------------------------------------------------------+",
            "void OnTick()",
            "  {",
            "   // Check if new bar",
            "   if(!IsNewBar()) return;",
            "   ",
            "   // Update risk management",
            "   UpdateRiskManagement();",
            "   ",
            "   // Check if trading is allowed",
            "   if(!tradingAllowed) return;",
            "   ",
            "   // Update indicator values",
            "   if(!UpdateIndicators()) return;",
            "   ",
            "   // Check for entry signals",
            "   int signal = GetEntrySignal();",
            "   ",
            "   // Execute trades based on signals",
            "   if(signal == 1) // Buy signal",
            "     {",
            "      if(CanOpenPosition(ORDER_TYPE_BUY))",
            "        {",
            "         OpenPosition(ORDER_TYPE_BUY);",
            "        }",
            "     }",
            "   else if(signal == -1) // Sell signal",
            "     {",
            "      if(CanOpenPosition(ORDER_TYPE_SELL))",
            "        {",
            "         OpenPosition(ORDER_TYPE_SELL);",
            "        }",
            "     }",
            "   ",
            "   // Check for exit signals",
            "   CheckExitSignals();",
            "  }",
            "",
        ]
    
    def _generate_strategy_functions(self, params: Dict[str, Any]) -> List[str]:
        """Generate strategy-specific functions."""
        return [
            "//+------------------------------------------------------------------+",
            "//| Strategy Functions                                               |",
            "//+------------------------------------------------------------------+",
            "",
            "//+------------------------------------------------------------------+",
            "//| Get entry signal based on optimized parameters                   |",
            "//+------------------------------------------------------------------+",
            "int GetEntrySignal()",
            "  {",
            "   // Implement your optimized strategy logic here",
            "   // This is a template - customize based on your strategy",
            "   ",
            "   // Example: Moving average crossover with ATR filter",
            "   if(ma_fast[1] > ma_slow[1] && ma_fast[2] <= ma_slow[2])",
            "     {",
            "      // Additional filters based on optimized parameters",
            f"      if(atr[1] > atr_len * {params.get('atr_len', 14)} * symbolInfo.Point())",
            "        {",
            "         return 1; // Buy signal",
            "        }",
            "     }",
            "   ",
            "   if(ma_fast[1] < ma_slow[1] && ma_fast[2] >= ma_slow[2])",
            "     {",
            f"      if(atr[1] > atr_len * {params.get('atr_len', 14)} * symbolInfo.Point())",
            "        {",
            "         return -1; // Sell signal",
            "        }",
            "     }",
            "   ",
            "   return 0; // No signal",
            "  }",
            "",
            "//+------------------------------------------------------------------+",
            "//| Check exit signals                                               |",
            "//+------------------------------------------------------------------+",
            "void CheckExitSignals()",
            "  {",
            "   for(int i = 0; i < PositionsTotal(); i++)",
            "     {",
            "      if(positionInfo.SelectByIndex(i))",
            "        {",
            "         if(positionInfo.Symbol() == Symbol() && positionInfo.Magic() == MagicNumber)",
            "           {",
            "            // Implement exit logic here",
            "            // Example: opposite signal closes position",
            "            int signal = GetEntrySignal();",
            "            ",
            "            if((positionInfo.PositionType() == POSITION_TYPE_BUY && signal == -1) ||",
            "               (positionInfo.PositionType() == POSITION_TYPE_SELL && signal == 1))",
            "              {",
            "               trade.PositionClose(positionInfo.Ticket());",
            "              }",
            "           }",
            "        }",
            "     }",
            "  }",
            "",
        ]
    
    def _generate_risk_management(self) -> List[str]:
        """Generate risk management functions."""
        return [
            "//+------------------------------------------------------------------+",
            "//| Risk Management Functions                                        |",
            "//+------------------------------------------------------------------+",
            "",
            "//+------------------------------------------------------------------+",
            "//| Update risk management variables                                 |",
            "//+------------------------------------------------------------------+",
            "void UpdateRiskManagement()",
            "  {",
            "   currentEquity = AccountInfoDouble(ACCOUNT_EQUITY);",
            "   ",
            "   if(currentEquity > maxEquity)",
            "     {",
            "      maxEquity = currentEquity;",
            "     }",
            "   ",
            "   currentDrawdown = (maxEquity - currentEquity) / maxEquity * 100.0;",
            "   ",
            "   // Disable trading if maximum drawdown exceeded",
            "   if(currentDrawdown > MaxDrawdown)",
            "     {",
            "      tradingAllowed = false;",
            "      Print(\"Trading disabled due to maximum drawdown: \", currentDrawdown, \"%\");",
            "     }",
            "  }",
            "",
            "//+------------------------------------------------------------------+",
            "//| Calculate position size based on risk                           |",
            "//+------------------------------------------------------------------+",
            "double CalculatePositionSize(double stopLossPoints)",
            "  {",
            "   if(LotSize > 0) return LotSize; // Fixed lot size",
            "   ",
            "   double equity = AccountInfoDouble(ACCOUNT_EQUITY);",
            "   double riskAmount = equity * RiskPercent / 100.0;",
            "   double tickValue = symbolInfo.TickValue();",
            "   double tickSize = symbolInfo.TickSize();",
            "   ",
            "   double riskPerLot = stopLossPoints * tickValue / tickSize;",
            "   double lotSize = riskAmount / riskPerLot;",
            "   ",
            "   // Normalize lot size",
            "   double lotStep = symbolInfo.LotsStep();",
            "   lotSize = NormalizeDouble(lotSize / lotStep, 0) * lotStep;",
            "   ",
            "   // Apply limits",
            "   double minLot = symbolInfo.LotsMin();",
            "   double maxLot = symbolInfo.LotsMax();",
            "   ",
            "   return MathMax(minLot, MathMin(maxLot, lotSize));",
            "  }",
            "",
            "//+------------------------------------------------------------------+",
            "//| Check if can open new position                                  |",
            "//+------------------------------------------------------------------+",
            "bool CanOpenPosition(ENUM_ORDER_TYPE orderType)",
            "  {",
            "   // Check maximum positions",
            "   int currentPositions = 0;",
            "   for(int i = 0; i < PositionsTotal(); i++)",
            "     {",
            "      if(positionInfo.SelectByIndex(i))",
            "        {",
            "         if(positionInfo.Symbol() == Symbol() && positionInfo.Magic() == MagicNumber)",
            "           {",
            "            currentPositions++;",
            "           }",
            "        }",
            "     }",
            "   ",
            "   return currentPositions < MaxPositions;",
            "  }",
            "",
        ]
    
    def _generate_utilities(self) -> List[str]:
        """Generate utility functions."""
        return [
            "//+------------------------------------------------------------------+",
            "//| Utility Functions                                               |",
            "//+------------------------------------------------------------------+",
            "",
            "//+------------------------------------------------------------------+",
            "//| Check if new bar                                                |",
            "//+------------------------------------------------------------------+",
            "bool IsNewBar()",
            "  {",
            "   datetime currentTime = iTime(Symbol(), PERIOD_CURRENT, 0);",
            "   if(currentTime != lastBarTime)",
            "     {",
            "      lastBarTime = currentTime;",
            "      return true;",
            "     }",
            "   return false;",
            "  }",
            "",
            "//+------------------------------------------------------------------+",
            "//| Update indicator values                                         |",
            "//+------------------------------------------------------------------+",
            "bool UpdateIndicators()",
            "  {",
            "   if(CopyBuffer(handleMA_Fast, 0, 0, 3, ma_fast) < 3) return false;",
            "   if(CopyBuffer(handleMA_Slow, 0, 0, 3, ma_slow) < 3) return false;",
            "   if(CopyBuffer(handleATR, 0, 0, 2, atr) < 2) return false;",
            "   ",
            "   return true;",
            "  }",
            "",
            "//+------------------------------------------------------------------+",
            "//| Open position                                                   |",
            "//+------------------------------------------------------------------+",
            "bool OpenPosition(ENUM_ORDER_TYPE orderType)",
            "  {",
            "   double price = (orderType == ORDER_TYPE_BUY) ? symbolInfo.Ask() : symbolInfo.Bid();",
            "   double stopLoss = 0, takeProfit = 0;",
            "   ",
            "   // Calculate stop loss and take profit",
            "   if(UseStopLoss || UseTakeProfit)",
            "     {",
            "      double atrValue = atr[1];",
            "      double slDistance = atrValue * 2.0; // 2 ATR stop loss",
            "      double tpDistance = atrValue * 3.0; // 3 ATR take profit",
            "      ",
            "      if(orderType == ORDER_TYPE_BUY)",
            "        {",
            "         if(UseStopLoss) stopLoss = price - slDistance;",
            "         if(UseTakeProfit) takeProfit = price + tpDistance;",
            "        }",
            "      else",
            "        {",
            "         if(UseStopLoss) stopLoss = price + slDistance;",
            "         if(UseTakeProfit) takeProfit = price - tpDistance;",
            "        }",
            "     }",
            "   ",
            "   // Calculate position size",
            "   double lotSize = CalculatePositionSize(MathAbs(price - stopLoss) / symbolInfo.Point());",
            "   ",
            "   // Open position",
            "   bool result = trade.PositionOpen(Symbol(), orderType, lotSize, price, stopLoss, takeProfit, TradeComment);",
            "   ",
            "   if(result)",
            "     {",
            "      Print(\"Position opened: \", EnumToString(orderType), \" \", lotSize, \" lots at \", price);",
            "     }",
            "   else",
            "     {",
            "      Print(\"Failed to open position: \", trade.ResultRetcode(), \" - \", trade.ResultRetcodeDescription());",
            "     }",
            "   ",
            "   return result;",
            "  }",
            "",
            "//+------------------------------------------------------------------+",
        ]
    
    def _get_mql5_type(self, param_name: str, value: Any) -> str:
        """Infer appropriate MQL5 input type for a parameter using name and value."""
        name = param_name.lower()

        # Explicit name-based mapping first (prevents numeric-looking strings from becoming string inputs)
        if (name.endswith(('_min_len', '_max_len', '_len')) or
            name.endswith('len') or
            any(k in name for k in ['period', 'lookback', 'bars', 'window'])):
            return 'int'

        if any(k in name for k in ['mult', 'ratio', 'threshold', 'factor']):
            return 'double'

        if name.startswith(('use', 'enable', 'disable')):
            return 'bool'

        # Fallback to value-based inference
        if isinstance(value, bool):
            return 'bool'
        if isinstance(value, int):
            return 'int'
        if isinstance(value, float):
            return 'double'
        
        # Strings that look like numbers: try to infer
        if isinstance(value, str):
            v = value.strip()
            # Detect boolean-like strings
            if v.lower() in ('true', 'false', 'yes', 'no', '1', '0'):
                return 'bool'
            # Detect integer-like
            try:
                # Accept forms like "12", "12.0"
                f = float(v)
                if f.is_integer():
                    return 'int'
                return 'double'
            except Exception:
                return 'string'

        return 'string'

    def _coerce_value_for_type(self, value: Any, mql_type: str) -> Any:
        """Coerce Python value to an appropriate Python type for the target MQL type."""
        try:
            if mql_type == 'bool':
                if isinstance(value, bool):
                    return value
                if isinstance(value, Number):
                    return bool(value)
                if isinstance(value, str):
                    v = value.strip().lower()
                    if v in ('true', 'yes', '1'):
                        return True
                    if v in ('false', 'no', '0'):
                        return False
                return False
            if mql_type == 'int':
                if isinstance(value, int):
                    return value
                if isinstance(value, Number):
                    return int(round(float(value)))
                if isinstance(value, str):
                    v = value.strip()
                    # Allow "12", "12.0"
                    f = float(v)
                    return int(round(f))
                return 0
            if mql_type == 'double':
                if isinstance(value, Number):
                    return float(value)
                if isinstance(value, str):
                    v = value.strip()
                    return float(v)
                return 0.0
            # string
            if value is None:
                return ''
            return str(value)
        except Exception:
            # Conservative defaults on parse failure
            if mql_type == 'bool':
                return False
            if mql_type == 'int':
                return 0
            if mql_type == 'double':
                return 0.0
            return ''

    def _format_mql5_literal(self, value: Any, mql_type: str) -> str:
        """Format a Python value as an MQL5 literal for the given type."""
        if mql_type == 'bool':
            return 'true' if bool(value) else 'false'
        if mql_type == 'int':
            try:
                return str(int(value))
            except Exception:
                return '0'
        if mql_type == 'double':
            try:
                # Compact yet precise representation
                return ("%g" % float(value))
            except Exception:
                return '0.0'
        # string
        s = '' if value is None else str(value)
        s = s.replace('\\', '\\\\').replace('"', '\\"')
        return f'"{s}"'
    
    def _get_parameter_comment(self, param_name: str) -> str:
        """Get descriptive comment for a parameter."""
        comments = {
            'fast_min_len': 'Fast MA minimum length',
            'fast_max_len': 'Fast MA maximum length', 
            'slow_min_len': 'Slow MA minimum length',
            'slow_max_len': 'Slow MA maximum length',
            'atr_len': 'ATR period',
            'dma_atr_len': 'DMA ATR period',
            'upper_outer_mult': 'Upper outer band multiplier',
            'lower_outer_mult': 'Lower outer band multiplier',
            'upper_inner_mult': 'Upper inner band multiplier',
            'lower_inner_mult': 'Lower inner band multiplier',
            'momentum_len': 'Momentum period',
            'momentum_threshold': 'Momentum threshold'
        }
        return comments.get(param_name, f'Optimized {param_name}')

    def _select_param_expr(self, params: Dict[str, Any], candidates: List[str], default_value: int | float) -> str:
        """Return the MQL5 expression to use for a parameter: prefer an input name that exists, else a literal.

        This prevents referencing undeclared identifiers when a particular parameter name is absent.
        """
        for name in candidates:
            if name in params:
                return name
        # Fallback to numeric literal
        if isinstance(default_value, int):
            return str(default_value)
        try:
            return ("%g" % float(default_value))
        except Exception:
            return "0"
